colon_lists:
  - ACLOCAL_PATH
  - BASHOPTS
  - CDPATH
  - CMAKE_PREFIX_PATH
  - CPATH
  - CPLUS_INCLUDE_PATH
  - C_INCLUDE_PATH
  - DYLD_LIBRARY_PATH
  - EC_CMAKE_MODULE_PATH
  - INFOPATH
  - LD_LIBRARY_PATH
  - LIBPATH
  - LIBRARY_PATH
  - LOADEDMODULES
  - MANPATH
  - MODULEPATH
  - NLSPATH
  - OBJC_INCLUDE_PATH
  - PATH
  - PKG_CONFIG_PATH
  - PYTHONPATH
  - SHELLOPTS
  - TCL_LIBRARY
# space_lists:
ignored_variables:
  - BASHPID
  - BASH_SUBSHELL
  - EPOCHREALTIME
  - EPOCHSECONDS
  - RANDOM
  - SECONDS
  - SRANDOM
ignored_normal_arrays:
  - BASH_LINENO
ignored_assoc_arrays:
  - BASH_CMDS
