#+TITLE: env-diff-compare

* NAME

env-diff-compare - Display the differences between two environments in human readable form

* SYNOPSIS

#+begin_src shell
env-diff-compare [options] BEFORE AFTER
#+end_src

* DESCRIPTION

Display the difference between two envrionments saved with =env-diff-save=.

* CONFIGURATION

See CONFIGURATION section of =env-diff --help=.

* OPTIONS

Note: Options must come before =CMD=

** ~--list-diff~

For 'colon list' variables, they will be compared using set comparison which
ignores doubles, order, and empty elements (caused by leading colon, trailing
colon, or two consecutive colons).

** ~--show-function-bodies~

For added functions, show the entire body of the function.

For modified functions, show an inline diff (like =git diff=) between the
initial and final versions of the function.

The function's code is obtained using the =type= bash builtin.  It may have
minor differences between the actual code in the file where the function is
defined.

** ~--no-ignore~

Disables the ignoring of changes to certain special variables.

Some variables are special and change no matter what like =BASHPID= (running
=CMD= and saving the final state happens in a subshell where =BASHPID= will
be different).

** ~--keep-tmpdir~

Do not delete the temporary directory used to save states before and after
=CMD=.  These directories can rise to 10M in size if there are a lot of shell
functions.  Each function must be saved in its own file to garantee no parsing
errors.  Although the file may be smaller it has to take one block (usually
4k) on disc.

** ~-F CONFIG_FILE~

Specify an alternate config file.

** ~--help~

Display this manpage and exit

* CAVEATS

Due to limitations in how =env-diff-save= can save traps as described in the
CAVEATS section of =env-diff --help=.

* SPECIAL VARIABLES

See =env-diff --help=.  For code generation special variables cannot be
configured.

* DEPENDENCIES

- jq
- standard UNIX tools (sort, comm, cut, cat, mkdir, mktemp)
- python3

Optionally if the python package =pygments= is available, it will be used to
hightlight the body of new shell functions.

The python package =pyyaml= (=python3 -m pip install [--user] pyyaml=) must be
installed to read the config file =~/.config/env-diff.yml=.

* AUTHOR

Philippe Carphin


